version: "3.9"
services:
  frontend:
    build:
      context: .
      args:
        VITE_INVESTMENT_API_URL: ${VITE_INVESTMENT_API_URL}
        VITE_FASTAPI_INVESTMENT_API_KEY: ${VITE_FASTAPI_INVESTMENT_API_KEY}
    ports:
      - "5173:80"
